Feature portfolio
ibrahim777764/my-portfoliom pull request #3
Opened 2022-02-10 23:06 UTC by ibrahim777764

2022-02-10 23:09 UTC, ibrahim777764 commented
please review my code, and let me know if there any changes ,thankyou

2022-02-10 23:57 UTC, Lordkaito requested changes
Hi @ibrahim777764, 

<img src="https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif" width="250px" height="200px">

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-10 23:57 UTC, Lordkaito commented on README.md
> +### Deployment
- [ ] [OPTIONAL] It is a good practice to keep your Readme file organized and clean, so please make sure to delete all the unused sections of this file.

2022-02-10 23:57 UTC, Lordkaito commented on porthtml.html
> +    <section class="sec1">
- [ ] Please make sure you follow the design as much as possible and include the background images as in the given template for this section.

2022-02-10 23:57 UTC, Lordkaito commented on porthtml.html
> +<body class="body1">
- [ ] Please try to keep all the margins as in the given template. Here, your logo and the hamburger menu are not following the template, as in the given design both of them have some margin which makes them not to be right on the border of the page, so kindly fix this issue. The same thing happens with the section, so please make sure to fix it there too.

2022-02-11 09:24 UTC, ibrahim777764 commented
please check my code,hope so now there is not reuqirments left,thankyou

2022-02-11 09:42 UTC, gemmen29 requested changes
Hi @ibrahim777764, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 09:42 UTC, gemmen29 commented on porthtml.html
> +</main>
Please try to match Figma design as match as possible in the background, font size, line height, and social media icons
| Your design | Figma design |
| --- | --- |
| ![screencapture-raw-githack-ibrahim777764-my-portfoliom-feature-portfolio-porthtml-html-2022-02-11-11_29_46](https://user-images.githubusercontent.com/24703171/153568365-3d354c66-8fd5-497a-9d4e-5c97937676d8.png) | ![Template 2-Mobile-Main](https://user-images.githubusercontent.com/24703171/153568749-4b3cae09-637e-4ba1-bb52-390cc6356f17.png) |

2022-02-11 09:42 UTC, gemmen29 commented on README.md
> +>>>>>>> 4207069f26825060634c6a9169d4394f5735aec4
[OPTIONAL] Kindly try to remove lines `16`, `22` and `23` in your README file as it added when there are conflict in your branch

2022-02-11 12:32 UTC, ibrahim777764 commented
please code review , hope so this time it's all good,thankyou

2022-02-11 12:46 UTC, alexander16108 approved these changes
Hi @ibrahim777764 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 12:59 UTC, merged